project:
  type: website
  output-dir: docs

website:
  title: "Elise Rust"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About Me
      - href: reading.qmd
        text: Reading List
      - href: thesis.qmd
        text: Undergraduate Thesis
      - href: mdi.qmd
        text: Massive Data Institute
      - href: https://eliserust.github.io/sentiment-analysis-reddit/eda.html
        text: Reddit Sentiment Analysis
      - href: cherry_blossoms.qmd
        text: Cherry Blossoms
      - href: fake_news.qmd
        text: Fake News Detection
      - href: https://eliserust.github.io/EnergyForecasting/
        text: Climate Time Series Project
      - href: nn.qmd
        text: Derby ANN
      - href: covid.qmd
        text: COVID-19 Vulnerabilities
        

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

body-header: |
  ![](dartmouth.png)

layouts:
  default:
    output:
      html_document:
        css: styles.css
        includes:
          in_header: custom_styles.css
        toc: true
  index:
    output:
      html_document:
        css: styles.css
        includes:
          in_header: custom_styles.css
        toc: false

